version: '3.8'
services:
  server:
    build:
      context: .
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      postrgres-ztcc:
        condition: service_healthy
    environment:
        POSTGRES_HOST: postrgres-ztcc
  postrgres-ztcc:
    image: postgres:11.5
    restart: always
    container_name: postrgres-ztcc
    ports:
      - $POSTGRES_DOCKER_PORT:$POSTGRES_LOCAL_PORT
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5